stages:
  - build

variables:
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

build doc:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $RELEASE_IMAGE .
    - docker tag $RELEASE_IMAGE "$CI_REGISTRY_IMAGE:latest"
    - docker push $RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - /master/
    - tags
  environment: development
  tags:
    - docker
